"""Regenerate the dashboard's inline brand mark from designs/logo.png.

Keys the white background to transparent, crops to the icon mark (dropping the
"Gene Program Interpreter" wordmark, which the dashboard header already shows as
text), downscales, and writes:

* designs/logo_mark.png      — the transparent mark (for reuse / inspection)
* gpi/_logo_data.py          — LOGO_MARK_DATA_URI, inlined into the page

Pure PIL (no numpy). Run:  python scripts/make_logo.py
"""
import base64
import io
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "designs" / "logo.png"
OUT_MARK = ROOT / "designs" / "logo_mark.png"
OUT_PY = ROOT / "gpi" / "_logo_data.py"

WORK_H = 320       # work at this height for speed; the mark ships smaller still
TARGET_H = 128     # exported mark height (displayed ~40px, so ~3x for retina)


def key_white(img):
    """Return an RGBA copy with the near-white, near-neutral background keyed out."""
    img = img.convert("RGBA")
    px = img.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, _ = px[x, y]
            mn = min(r, g, b)
            sat = max(r, g, b) - mn
            if mn >= 244 and sat <= 12:            # solid background
                px[x, y] = (r, g, b, 0)
            elif mn >= 225 and sat <= 18:          # anti-aliased edge -> feather
                a = int(round((244 - mn) * 255.0 / (244 - 225)))
                px[x, y] = (r, g, b, max(0, min(255, a)))
    return img


def opaque_columns(img, thresh=20):
    px = img.load()
    w, h = img.size
    return [any(px[x, y][3] > thresh for y in range(h)) for x in range(w)]


def runs_from(flags, gap=6):
    idx = [i for i, v in enumerate(flags) if v]
    if not idx:
        return []
    runs, start, prev = [], idx[0], idx[0]
    for c in idx[1:]:
        if c - prev > gap:
            runs.append((start, prev))
            start = c
        prev = c
    runs.append((start, prev))
    return runs


def main():
    im = Image.open(SRC)
    W, H = im.size
    work = im.resize((round(W * WORK_H / H), WORK_H), Image.LANCZOS)
    keyed = key_white(work)

    cols = opaque_columns(keyed)
    runs = runs_from(cols)
    runs.sort(key=lambda p: p[1] - p[0], reverse=True)   # widest first
    x0, x1 = sorted(runs[:2], key=lambda p: p[0])[0]     # leftmost of the two widest = the mark

    px = keyed.load()
    w, h = keyed.size
    rows = [y for y in range(h) if any(px[x, y][3] > 20 for x in range(x0, x1 + 1))]
    y0, y1 = rows[0], rows[-1]

    crop = keyed.crop((x0, y0, x1 + 1, y1 + 1))
    pad = 4
    canvas = Image.new("RGBA", (crop.width + 2 * pad, crop.height + 2 * pad), (0, 0, 0, 0))
    canvas.paste(crop, (pad, pad), crop)
    scale = TARGET_H / canvas.height
    canvas = canvas.resize((round(canvas.width * scale), TARGET_H), Image.LANCZOS)
    canvas.save(OUT_MARK, optimize=True)

    buf = io.BytesIO()
    canvas.save(buf, "PNG", optimize=True)
    uri = "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()

    with open(OUT_PY, "w") as f:
        f.write('"""Auto-generated by scripts/make_logo.py from designs/logo.png\n')
        f.write("(white keyed to transparent, cropped to the icon mark). Do not edit\n")
        f.write('the base64 by hand — rerun the script instead."""\n\n')
        f.write("LOGO_MARK_DATA_URI = (\n")
        for i in range(0, len(uri), 100):
            f.write("    %r\n" % uri[i:i + 100])
        f.write(")\n")

    print("runs:", runs)
    print("mark x-range:", (x0, x1), "crop:", crop.size, "-> export:", canvas.size)
    print("data-URI KB:", round(len(uri) / 1024, 1))


if __name__ == "__main__":
    main()
